### ISSUE TITLE
web app can't be started

### ISSUE THREAD

**Issue by hamsterksu** [opencellsoft/juju-charms#1]
hi 

i'm trying to deploy this charm to my env.
but i have got errors: 

`Caused by: java.lang.ClassNotFoundException: org.drools.KnowledgeBase from [Module "deployment.meveo.war:main" from Service Module Loader]`

`Caused by: java.lang.ClassNotFoundException: org.drools.runtime.ObjectFilter from [Module "deployment.meveo.war:main" from Service Module Loader]`

`Caused by: java.lang.ClassNotFoundException: com.ocpsoft.pretty.faces.spi.ConfigurationProvider from [Module "deployment.meveo.war:main" from Service Module Loader]`

i used version "current" and "4.1.2" the same error in both cases

**Comment by antoinemichea** [comment]
Hi @hamsterksu.
It's not a bug, it's only an INFO log.

**Comment by hamsterksu** [comment]
after this jboss is killed.

**Comment by antoinemichea** [comment]
can you please send me full log ?

**Comment by hamsterksu** [comment]
hi @antoinemichea,

seems it was my fault. i think i used machine with small resources. it was 1G ram
Today i deployed charm to machine with 2G ram. now it works.

thanks,

**Comment by antoinemichea** [comment]
Ho yes,
At least your jboss need to start with a minimum of 1,3Go of memory. If you only have 1Go of RAM you can use swap on filesystem but but it's very slow.
Thanks for you feedback @hamsterksu !
